name: DwarfStar
main: me.alchemi.dwarfstar.main
version: ${project.version}
author: Alchemi
description: "\"He wrapped my father in unbreakable chains forged in the heart of a dwarf star.\"\nA plugin made for LuukDMM, this plugin creates commands for smelting ores etc."
depend: [AlchemicLibrary]

commands:
  smelter:
    description: Smelt stuff!
    aliases: [smelter, smelt]
    permission: dwarfstar.smelt
    usage: /smelt [hand|inventory|amount]
  
  dwarfstar:
    description: DwarfStar base command
    aliases: [dwarfstar, dws]
    permission: dwarfstar.admin
    usage: /dwarfstar
  
permissions:
  dwarfstar.admin:
    description: Admin permission
    default: op
    
  dwarfstar.admin.create:
    description: Permission to create a recipe
    default: op
  
  dwarfstar.admin.delete:
    description: Permission to delete a recipe
    default: op
    
  dwarfstar.admin.edit:
    description: Permission to edit a recipe
    default: op

  dwarfstar.smelt:
    description: Permission to smelt
    default: true